### ISSUE TITLE
Error message: Sources import - Error 5 Cannot parse version and build number 

### ISSUE THREAD

**Issue by kalias29** [Appollo-CLI/Appollo#10]
I tried to build start and after some time this error appears, but my pubsec yaml has no errors. Here it is:
```
name: escape_room
description: Escape Room

 
publish_to: 'none'  
version: 2.0.5+12

environment:
  sdk: ">=2.17.0 <3.0.0"

 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.3
  gsheets: ^0.4.2
  uuid: ^3.0.6
  intl: ^0.17.0
  connectivity_plus: ^2.3.0
  hexcolor: ^2.0.7
  marquee: ^2.2.2
  http: ^0.13.4
  html: ^0.15.0
   
 
  flutter_staggered_animations: ^1.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  like_button: ^2.0.4
  timer_count_down: ^2.2.1
   
   
 
  change_app_package_name: ^1.1.0
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  flutterfire_ui: ^0.4.1+2
  google_sign_in: ^5.3.3
  animated_text_kit: ^4.2.2
  avatar_glow: ^2.0.2
  flutter_zoom_drawer: ^3.0.2
  url_launcher: ^6.1.3
  flutter_native_splash: ^2.2.3+1
  icons_plus: ^2.0.1
  new_version: ^0.3.1
  package_info_plus: ^1.4.2
  firebase_messaging: ^11.4.2
  firebase_auth: ^3.3.20
  google_mobile_ads: ^1.3.0
  permission_handler: ^10.0.0
  smooth_page_indicator: ^1.0.0+2
  app_settings: ^4.1.8
  provider: ^6.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo512.png"
 
flutter:

 
  uses-material-design: true
 
  assets:
    - assets/
    

```
